[[battery.display]]  # "bold red" style when capacity is between 0% and 10%
threshold = 10
style = "bold red"

[[battery.display]]  # "bold yellow" style when capacity is between 10% and 30%
threshold = 30
style = "bold yellow"

# when capacity is over 30%, the battery indicator will not be displayed

[character]
style_success = "bold #FAA916"
style_failure = "bold #621708"

[directory]
style = "bold #A44200"

[git_branch]
style = "bold #D58936"

[git_commit]
style = "bold #FFAA5A"
disabled = false

#[time]
#style = "dimmed #6D676E"
#disabled = false

[package]
disabled = true

[java]
disabled = true

[nodejs]
disabled = true
